set(CMAKE_CXX_STANDARD 20)

if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    set( CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -W3 -WX -w44834 -w34189 -w34100 -w34715 -w34244 -EHsc" )
endif ()

if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Werror -Wextra")
endif ()
