name: Build main
on:
  push:
    branches:
      - main
jobs:
  ubuntu-gcc-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo apt-get install g++-9
        sudo apt-get install python3-pip
        sudo python3 -m pip install --upgrade pip
        pip3 install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: RunTests
      run: |
        mkdir -p build/tests_ref
        export BUILD_DIR=$GITHUB_WORKSPACE/build/
        python ./tests_ref/test.py
        cd build
        cmake ..
        make -j4
        mkdir tests_time
        cd bin
        ./Tests
        cd ../..
      env:
        CC: gcc-9
        CXX: g++-9
