name: Build main
on:
  push:
    branches:
      - main
jobs:
  ubuntu-gcc-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo apt-get install g++-9
        sudo apt-get install python3-pip
        sudo python3 -m pip install --upgrade pip
        pip3 install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Build
      run: |
        mkdir build
        cd build
        cd ..
    - name: RunTests
      run: |
        cd tests_ref
        python ./test.py
      env:
        CC: gcc-9
        CXX: g++-9
