name: Build application
on:
  push:
    branches-ignore:
    - main
  pull_request:
    branches-ignore:
    - main
jobs:
  ubuntu-gcc-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo apt-get install g++-9
        sudo apt-get install python3-pip
        sudo python3 -m pip install --upgrade pip
        pip3 install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: RunTestsOpt
      run: |
        mkdir -p build/tests_ref
        export BUILD_DIR=$GITHUB_WORKSPACE/build/
        python ./tests_ref/test.py
        cd build
        cmake ..
        make -j4
        mkdir tests_time
        cd bin
        ./Tests
    - name: RunTestsRef
      run: |
        git checkout main
        mkdir -p build-main/tests_ref
        export BUILD_DIR=$GITHUB_WORKSPACE/build-main/
        python ./tests_ref/test.py
        cd build-main
        cmake ..
        make -j4
        mkdir -p tests_time
        cd bin
        ./Tests
    - name: Checker
      run: |
        cd build/bin
        ./Checker $GITHUB_WORKSPACE/build-main/tests_time/tests_time.txt $GITHUB_WORKSPACE/build/tests_time/tests_time.txt
      env:
        CC: gcc-9
        CXX: g++-9
