name: Build application
on:
  push:
    branches-ignore:
    - main
  pull_request:
    branches-ignore:
    - main
jobs:
  ubuntu-gcc-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo apt-get install g++-9
        sudo apt-get install python3-pip
        sudo python3 -m pip install --upgrade pip
        pip3 install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: RunReferenceTests
      run: |
        mkdir build
        export BUILD_DIR=$GITHUB_WORKSPACE/build/
        cd build
        mkdir tests_ref
        cd ../tests_ref
        python ./test.py
        cd ../build/tests_ref
        ls -la
        cd ../..
    - name: Build
      run: |
        cd build
        cmake ..
        make -j4
        cd ..
    - name: RunTests
      run: |
        export BUILD_DIR=$GITHUB_WORKSPACE/build/
        cd build/bin
        ./Tests
      env:
        CC: gcc-9
        CXX: g++-9
  ubuntu-clang-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo apt-get install clang-8
        sudo apt-get install python3-pip
        sudo python3 -m pip install --upgrade pip
        pip3 install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: RunReferenceTests
      run: |
        mkdir build
        export BUILD_DIR=$GITHUB_WORKSPACE/build/
        cd build
        mkdir tests_ref
        cd ../tests_ref
        python ./test.py
        cd ../build/tests_ref
        ls -la
        cd ../..
    - name: Build
      run: |
        cd build
        cmake ..
        make -j4
        cd ..
    - name: RunTests
      run: |
        export BUILD_DIR=$GITHUB_WORKSPACE/build/
        cd build/bin
        ./Tests
      env:
        CC: clang-8
        CXX: clang++-8